services:
  nginx:
    build: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    ports:
      - "3000:80"
    environment:
      TZ: "Asia/Tokyo"
    restart: always
  app:
    build:
      context: ./app
