version: "3"
services:
    wow:
        build: .
        ports:
            - "20001:3000"
        restart: always
        tty: true
        stdin_open: true
        environment:
            - FLAG=ping{FAKE}
