version: "3"
services:
    you-spin-me-round:
        build: .
        ports:
            - "20000:3000"
        restart: always
        tty: true
        stdin_open: true
        environment:
            - FLAG=ping{FAKE}
