services:
  uwsgi:
    build: ./app
    env_file:
      - .env
    expose:
      - "7777"
    restart: always
  nginx:
    build: ./nginx
    links:
      - uwsgi
    ports:
      - "4989:80"
    environment:
      TZ: "Asia/Tokyo"
    restart: always
